null tests
use !p instead of p==NULL

LAMP_HMM/hmmFind.cpp:120:19: error: no match for ‘operator==’ (operand types are ‘std::ifstream {aka std::basic_ifstream<char>}’ and ‘long int’)
         if(hmmFile==NULL){
                   ^

Gbp-Pq: Name 0005-null-tests.patch